(function() {var implementors = {};
implementors['intrusive_containers'] = ["impl&lt;L: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> + <a class='trait' href='intrusive_containers/linked_list/trait.Linkable.html' title='intrusive_containers::linked_list::Linkable'>Linkable</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='intrusive_containers/linked_list/struct.Links.html' title='intrusive_containers::linked_list::Links'>Links</a>&lt;L&gt;","impl&lt;T: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>, L: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='intrusive_containers/linked_list/struct.NodeImpl.html' title='intrusive_containers::linked_list::NodeImpl'>NodeImpl</a>&lt;T, L&gt;","impl&lt;P, T, S, L&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='intrusive_containers/linked_list/struct.LinkedList.html' title='intrusive_containers::linked_list::LinkedList'>LinkedList</a>&lt;P, T, S, L&gt;","impl&lt;'a, P, T, L: <a class='trait' href='intrusive_containers/linked_list/trait.Linkable.html' title='intrusive_containers::linked_list::Linkable'>Linkable</a>&lt;Container=T&gt;&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='intrusive_containers/linked_list/struct.Iter.html' title='intrusive_containers::linked_list::Iter'>Iter</a>&lt;'a, P, T, L&gt;","impl&lt;P, T, S, L&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='intrusive_containers/linked_list/struct.IntoIter.html' title='intrusive_containers::linked_list::IntoIter'>IntoIter</a>&lt;P, T, S, L&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
